### ISSUE TITLE
Cannot load NXCrypt.dll

### ISSUE THREAD

**Issue by zachhilman** [Reisyukaku/CDNNX#7]
I am running the latest commit. I had to alter the HTTP.cs file and add the switch password to the constructor for the cert. When I start it and click download, it gets to the the NCA3 nca3 = new NCA3(file) line and debug stepping into that it crashes on decryptHeader with the error cannot find dll. Any ideas?

**Comment by Reisyukaku** [comment]
There should be checks for that file on init, so thats not the issue, and if for some reason the DLL doesnt work on your machine, i'd imagine it'd throw an error in the aes/crypto class where i wrap the C dll to managed C#

**Comment by Reisyukaku** [comment]
I heard for some reason other people had to manually copy the dll into the same dir as the program, so on build that'd be the debug/release folder but i've always had this set, so not sure why it didnt work for others.
https://i.gyazo.com/1dceda29b0877726e9b20704c148bac4.png
Will close for now

**Comment by wchdsk** [comment]
I have the save problem that can't load NXCrypt.dll
When I look at NXCrypt.dll Import table and look's like it need libgcc_s_dw2-1.dll to load
so if someone have the same problem , you can copy this dll from QT or find it at internet

**Comment by Reisyukaku** [comment]
Very strange. Maybe its just  because by default projects require .Net 4.6 and you might not be up to date on that.

**Comment by nls44** [comment]
The problem is that the NXCrypt.dll indeed requires that .dll. Did you use MingW to compile it? Is it possible to statically link it so we don't have to install MingW ourselves to get that DLL?

**Comment by Reisyukaku** [comment]
MinGW doesnt make the program/dll reliant on anything like cygwin does.. nonetheless, im working on just writting a C# crypto lib since too many win10 users complain of dll issues.
