### ISSUE TITLE
[SUGGESTION] [nice-to-have] Proxy support

### ISSUE THREAD

**Issue by tiliarou** [Reisyukaku/CDNNX#8]
This is just a suggestion and quite overkill but would it be feasible and not too time consuming to add proxy support ? (HTTP/HTTPS authenticated  and SOCKS4/5 proxy support since I guess it takes windows default)
It's really a nice to have feature and absolutely not needed by most but in case it's not difficult, just giving suggestion.
Thanks.

**Comment by Reisyukaku** [comment]
I'd imaging just using a vpn would be the cleanest method to do that. Havent really looked into this kind kind of thing in C# yet.

**Comment by tiliarou** [comment]
Yes, it's a clean and fast workaround. Can use proxify or similar as well to force proxying on per app basis.
Nevermind, this is really something that a minority would use.
And it's very annoying I believe in C#.
Don't bother ;)
